-- PATIENTS TABLE
CREATE TABLE PATIENTS (
  ID INT GENERATED ALWAYS AS IDENTITY,
  NAME VARCHAR(255) NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  PRIMARY KEY (ID)
);

-- MEDICAL_HISTORIES TABLE

CREATE TABLE MEDICAL_HISTORIES (
  ID INT GENERATED ALWAYS AS IDENTITY,
  ADMITTED_AT TIMESTAMP NOT NULL,
  PATIENT_ID INT,
  STATUS VARCHAR(255),
  PRIMARY KEY (ID),
  CONSTRAINT FK_PATIENTS
  FOREIGN KEY (PATIENT_ID)
  REFERENCES PATIENTS(ID)
);

-- TREATMENTS TABLE

CREATE TABLE TREATMENTS (
  ID INT GENERATED ALWAYS AS IDENTITY,
  TYPE VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

-- MEDICAL_HISTORIES, TREATMENTS JOIN TABLE

CREATE TABLE MEDICAL_HISTORIES_TREATMENTS (
  MEDICAL_HISTORY_ID INT NOT NULL,
  TREATMENT_ID INT NOT NULL,
  PRIMARY KEY (MEDICAL_HISTORY_ID, TREATMENT_ID),
  CONSTRAINT FK_MEDICAL_HISTORIES
  FOREIGN KEY (MEDICAL_HISTORY_ID)
  REFERENCES MEDICAL_HISTORIES(ID),
  CONSTRAINT FK_TREATMENT
  FOREIGN KEY (TREATMENT_ID)
  REFERENCES TREATMENTS(ID)
);
